@startuml Zustandsdiagramm - Kunde ist ausgeloggt

hide empty description

state index.html {
    index.html: token
    index.html: roles
    index.html: expiresIn
    index.html: tokenIssuedAt

    [*] -down-> Login: Menüpunkt/Button "Login" anklicken
    [*] --> BuchSuchen: Button "Bücher suchen" anklicken
    [*] -down-> BuchSuchen: Menüpunkt "Buch Suchen" anklicken

    state Login {
        [*] --> Loginformular: Anmeldedaten eingeben
        Loginformular --> Wartend: Button "Anmelden" anklicken
        state AnmeldungAntwortChoice <<choice>>
        Wartend --> AnmeldungAntwortChoice: Anmeldeantwort eingetroffen

        state Anmeldeantwort {
            AnmeldungAntwortChoice --> LoginErfolgreich: Korrekte Daten eingegeben
            AnmeldungAntwortChoice --> FehlermeldungAnmeldung: Falsche Anmeldedaten eingegeben oder Error
        }
    }
    LoginErfolgreich -right-> BuchSuchen : Menüpunkt "Buch Suchen" anklicken

    state BuchSuchen {

    }
    Login -right[hidden]-> BuchSuchen


    state BuchSuchen {
        [*] --> Eingabefeld: Id, Titel oder Teiltitel eingeben
        Eingabefeld --> Waiting_Eigabe : Button "Suchen"
        state SuchergebnisEingabe <<choice>>
        Waiting_Eigabe --> SuchergebnisEingabe: Suchergebnis eingetroffen

        state SuchergebnisEingabeFeld {
            SuchergebnisEingabe --> GefundeneBuecher: kein Error
        }

        [*] -left-> RadioButton: Auswählen
        RadioButton --> Waiting_RadioButton: Anfrage senden
         state SuchergebnisRadioButton <<choice>>
         Waiting_RadioButton --> SuchergebnisRadioButton: Suchergebnis eingetroffen

        state SuchergebnisRadioButtonTable {
            SuchergebnisRadioButton --> GefundeneBuecherRadio: kein Error
        }

        [*] --> CheckBox: Auswählen
        CheckBox --> Waiting_CheckBox: Anfrage senden
        state SuchergebnisCheckBox <<choice>>
         Waiting_CheckBox --> SuchergebnisCheckBox: Suchergebnis eingetroffen

         state SuchergebnisCheckboxTable {
            SuchergebnisCheckBox --> GefundeneBuecherCheck: kein Error
        }

        state Alert {
            SuchergebnisRadioButton --> Fehlermeldung: Error
            SuchergebnisEingabe --> Fehlermeldung: Error
            SuchergebnisCheckBox --> Fehlermeldung: Error
        }

         GefundeneBuecher -down-> DetailsBuch: Zeile anklicken
         GefundeneBuecherRadio -down-> DetailsBuch: Zeile anklicken
         GefundeneBuecherCheck -down-> DetailsBuch: Zeile anklicken
    }
}

footer (c) Gruppe 4

@enduml
