@startuml Zustandsdiagramm

hide empty description

state index.html {
    index.html: token
    index.html: roles
    index.html: expiresIn
    index.html: tokenIssuedAt

    [*] --> [*]: Logout
    [*] --> NeuesBuch: Bücher anlegen
    [*] --> BuchSuchen: Bücher suchen
    
    state BuchSuchen

    state NeuesBuch{
        state Waiting
        state Antwort
        state Fehlermeldung

        [*] --> Waiting: Daten eingeben
        [*] --> Fehlermeldung: Falsche Dateneingabe

        Waiting --> Antwort: Datensatz wurde angelegt
        Waiting -right-> Fehlermeldung: Fehler bei dem Datenanlegen 
    }
}

footer (c) Gruppe 4

@enduml
